name: base_project_flutter
description: "This Project is base project you can read more info in readme file what is included in it."
publish_to: 'none'
version: 1.0.1+2  #[ChangeAppVersion]

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #storage
  shared_preferences: ^2.2.3

  #utils
  intl: ^0.19.0
  fk_user_agent: ^2.1.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1

  #network
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app.png"
  remove_alpha_ios: true
#  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/