name: base_project_flutter
description: "This Project is base project you can read more info in readme file what is included in it."
publish_to: 'none'
version: 1.0.0+1  #[ChangeAppVersion] Read @documentation/flutter.md

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Storage
  shared_preferences: ^2.2.3

  #Firebase Notification
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
